name: 构建并部署到 Github Pages

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  contents: write      # 需要写入权限推送到 gh-pages 分支
  pages: write
  id-token: write

env:
  STORE_PATH: ''

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Ubuntu 构建和推送
    runs-on: ubuntu-latest
    environment:
      name: 正式 Production - GitHub Pages
      url: https://nolebase.github.io/nolebase
    steps:
      - name: 签出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 安装 Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: 安装 pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: false
          version: 8

      - name: 获取 pnpm store 目录
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV


